### ISSUE TITLE
skid

### ISSUE THREAD

**Issue by Spigey** [handlersix/Token-Disable#2]
This is peak level skidding holy shit skidding a fucking design
evern the fucking repository name can you not come up with shit yourself

**Comment by handlersix** [comment]
sorry about ur issue! perhaps we can talk on spigeybackup? 😭

**Comment by Spigey** [comment]
spigeybackup is termed because scam alerts got termed?? it's just an account it's not that deep holy shit

**Comment by handlersix** [comment]
why are u getting mad its not that serious

**Comment by Spigey** [comment]
I'm not mad about losing my account nor my server bro

**Comment by handlersix** [comment]
it sounds like you are pretty mad right now
dont rage over github
